/**
 * Represents a chat channel within the application.
 */
export interface Channel {
  /**
   * The unique identifier of the channel (optional, typically generated by the database).
   */
  id?: string;
  /**
   * The name of the channel.
   */
  name: string;
  /**
   * A brief description of the channel's purpose (optional).
   */
  description?: string;
  /**
   * The ID of the user who created the channel.
   */
  created_by: string;
  /**
   * The timestamp indicating when the channel was created (optional).
   */
  created_at?: string;
}