import { User } from './user.interface';

/**
 * Represents a chat message within a channel or direct message thread.
 */
export interface Message {
  /**
   * The unique identifier of the message (optional, typically generated by the database).
   */
  id?: string;
  /**
   * The text content of the message.
   */
  content: string;
  /**
   * The ID of the user who sent the message.
   */
  sender_id: string;
  /**
   * The ID of the channel where the message was sent (optional, for channel messages).
   */
  channel_id?: string;
  /**
   * The ID of the recipient user (optional, for direct messages).
   */
  recipient_id?: string;
  /**
   * The timestamp indicating when the message was created (optional).
   */
  created_at?: string;
  /**
   * The ID of the parent message, if this message is part of a thread/reply (optional).
   */
  parent_id?: string;
  /**
   * Reactions registered on this message (optional).
   * Map of emoji character/reaction identifier to an array of user IDs who reacted.
   */
  reactions?: Record<string, string[]>;
  /**
   * The User object of the sender, resolved from the sender_id (optional).
   */
  sender?: User;
}
